# Stage 1: Build React app
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

#  This is the key
ARG MODE=prodx
RUN npm run build -- --mode=$MODE

# Stage 2: Serve using nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8037

CMD ["nginx", "-g", "daemon off;"]


# Nginx → a fast web server used to serve websites
# Alpine Linux → a very small Linux OS

# A lightweight container with Nginx installed
