# Stage 1: Build React app
FROM node:20-alpine AS build

WORKDIR /

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# 👇 This is the key
ARG MODE=qa
RUN npm run build -- --mode=qa

# Stage 2: Serve using nginx
FROM nginx:alpine

COPY --from=build /dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


# Nginx → a fast web server used to serve websites
# Alpine Linux → a very small Linux OS

# A lightweight container with Nginx installed